// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTKtSdMmYnmnxaDTRfzf5MavdaQf3ZklM',
    appId: '1:416267427191:web:85db6ad3952ec79a9f5572',
    messagingSenderId: '416267427191',
    projectId: 'mundial-5fee1',
    authDomain: 'mundial-5fee1.firebaseapp.com',
    storageBucket: 'mundial-5fee1.firebasestorage.app',
    measurementId: 'G-W9VPDYHBBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPe2IVc7n2DfBVOOhrpaIDEVT9uW2hGHY',
    appId: '1:416267427191:android:52b8da227cdb85dc9f5572',
    messagingSenderId: '416267427191',
    projectId: 'mundial-5fee1',
    storageBucket: 'mundial-5fee1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEg3jIerp4YsZendY9TPKVjP4hB3Vsf_4',
    appId: '1:416267427191:ios:f0878b8de3a052989f5572',
    messagingSenderId: '416267427191',
    projectId: 'mundial-5fee1',
    storageBucket: 'mundial-5fee1.firebasestorage.app',
    iosBundleId: 'com.example.mundialManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEg3jIerp4YsZendY9TPKVjP4hB3Vsf_4',
    appId: '1:416267427191:ios:f0878b8de3a052989f5572',
    messagingSenderId: '416267427191',
    projectId: 'mundial-5fee1',
    storageBucket: 'mundial-5fee1.firebasestorage.app',
    iosBundleId: 'com.example.mundialManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTKtSdMmYnmnxaDTRfzf5MavdaQf3ZklM',
    appId: '1:416267427191:web:f4b18437999598369f5572',
    messagingSenderId: '416267427191',
    projectId: 'mundial-5fee1',
    authDomain: 'mundial-5fee1.firebaseapp.com',
    storageBucket: 'mundial-5fee1.firebasestorage.app',
    measurementId: 'G-9S28L65YGB',
  );
}
